[package]
name = "task5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
scan_fmt = "0.2.6"
itertools = "0.10.1"
anyhow = "1.0.51"